# Generated by Django 5.0.2 on 2024-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_created', models.DateField(verbose_name='Link Creation Date')),
                ('link_taken_from', models.URLField(verbose_name='Link Taken From')),
                ('link_to', models.URLField(verbose_name='Link To')),
                ('anchor_text', models.CharField(max_length=255, verbose_name='Anchor Text')),
                ('status_of_link', models.CharField(choices=[('dofollow', 'Dofollow'), ('nofollow', 'Nofollow')], default='dofollow', max_length=8, verbose_name='Status of Link')),
            ],
        ),
    ]
