# Generated by Django 5.0.2 on 2024-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_taken_from',
        ),
        migrations.AddField(
            model_name='link',
            name='target_link',
            field=models.URLField(null=True, verbose_name='Target Link'),
        ),
    ]
