# Generated by Django 5.0.2 on 2024-02-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0004_link_issue_addressed_alter_link_status_of_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_crawl_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Crawl Date'),
        ),
    ]
