# Generated by Django 5.0.2 on 2024-02-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0005_link_last_crawl_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='manual_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='status_of_link',
            field=models.CharField(blank=True, choices=[('Dofollow', 'Dofollow'), ('Nofollow', 'Nofollow'), ('Source Removed', 'Source Removed'), ('Link Removed', 'Link Removed')], max_length=15, null=True, verbose_name='Status of Link'),
        ),
    ]
