# Generated by Django 5.0.2 on 2024-02-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0006_link_manual_edit_alter_link_status_of_link'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('target_link', 'link_to', 'anchor_text'), name='unique_link_combination'),
        ),
    ]
