# Generated by Django 4.2.7 on 2024-03-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0007_link_unique_link_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='index_status',
            field=models.CharField(blank=True, choices=[('Index', 'Indexed'), ('Not Index', 'Not Index')], max_length=11, null=True, verbose_name='Index Status'),
        ),
    ]
