# Generated by Django 4.2.7 on 2024-03-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0008_link_index_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkStatusThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Dofollow', 'Dofollow'), ('Nofollow', 'Nofollow'), ('Source Removed', 'Source Removed'), ('Link Removed', 'Link Removed')], max_length=15, unique=True, verbose_name='Link Status')),
                ('days_threshold', models.IntegerField(default=2, verbose_name='Days Threshold')),
            ],
        ),
    ]
