# Generated by Django 4.2.7 on 2024-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0012_alter_linkstatusthreshold_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_index_check',
            field=models.DateField(blank=True, null=True, verbose_name='Last Index Check'),
        ),
    ]
