# Generated by Django 4.2.7 on 2024-03-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0013_link_last_index_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_checker_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the API key', max_length=100)),
                ('key', models.CharField(help_text='The API key', max_length=255)),
            ],
        ),
    ]
