# Generated by Django 4.2.7 on 2024-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0014_index_checker_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index_checker_api',
            options={'verbose_name_plural': 'API Key'},
        ),
        migrations.RemoveField(
            model_name='index_checker_api',
            name='name',
        ),
        migrations.AlterField(
            model_name='index_checker_api',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
