# Generated by Django 4.2.7 on 2024-03-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0016_alter_link_status_of_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='address_status',
            field=models.CharField(choices=[('-', 'Blank'), ('addressed', 'Addressed')], default='-', max_length=10, verbose_name='Address Status'),
        ),
    ]
