# Generated by Django 4.2.7 on 2024-03-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0018_remove_link_issue_addressed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_to',
            field=models.CharField(verbose_name='Link To'),
        ),
        migrations.AlterField(
            model_name='link',
            name='target_link',
            field=models.CharField(null=True, verbose_name='Target Link'),
        ),
    ]
