# Generated by Django 4.2.7 on 2024-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0019_alter_link_link_to_alter_link_target_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='blogger_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Blogger Email'),
        ),
        migrations.AddField(
            model_name='link',
            name='blogger_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Blogger Name'),
        ),
    ]
