# Generated by Django 4.2.7 on 2024-04-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0020_link_blogger_email_link_blogger_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Email Api Key',
            },
        ),
    ]
