# Generated by Django 4.2.7 on 2024-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0022_alter_link_status_of_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_email_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Last Email Sent'),
        ),
    ]
