# Generated by Django 4.2.7 on 2024-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0023_link_last_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_Blogger_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('domain', models.CharField(editable=False, max_length=255)),
                ('blogger_name', models.CharField(max_length=100)),
                ('blogger_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='blogger_email',
        ),
        migrations.RemoveField(
            model_name='link',
            name='blogger_name',
        ),
    ]
