# Generated by Django 4.2.7 on 2024-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_crawler', '0025_alter_email_api_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status_of_link',
            field=models.CharField(blank=True, choices=[('Dofollow', 'Dofollow'), ('Nofollow', 'Nofollow'), ('404', '404'), ('Link Removed', 'Link Removed')], max_length=25, null=True, verbose_name='Status of Link'),
        ),
    ]
